name: Deploy Updated GCS Buckets

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Detect Changed .tfvars Files
        id: get-changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^terraform/user_vars/.*\.tfvars$' || true)
          CHANGED_USERS=$(echo "$CHANGED_FILES" | sed -E 's|terraform/user_vars/(.*)\.tfvars|\1|' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          if [ -z "$CHANGED_USERS" ]; then CHANGED_USERS="[]"; fi
          echo "::set-output name=changed_users::$CHANGED_USERS"
      - name: Debug Changed Users
        run: |
          echo "Changed Users: ${{ steps.get-changed-files.outputs.changed_users }}"

  deploy:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changed_users != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user: ${{ fromJson(needs.detect-changes.outputs.changed_users) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy User's Buckets
        run: |
          terraform init
          terraform apply -var-file="terraform/user_vars/${{ matrix.user }}.tfvars" -auto-approve

